name: Node.js CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]

    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }}"
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: echo "💻 Installing dependencies."
      - run: npm ci
      - run: echo "💅 Running linting."
      - run: npm run lint
      - run: echo "🧪 Running all the tests."
      - run: npm test --passWithNoTests
      - run: echo "🍏 This job's status is ${{ job.status }}."
